AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  FunctionName:
    Type: String

  RetentionInDays:
    Type: Number
    Default: 14

Resources:
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FunctionName}
      RetentionInDays: 14