AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CardReader/Application/Env

  TargetChannelId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CardReader/Application/TargetChannelId

Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
    MemorySize: 256
    AutoPublishAlias: !Ref Env
    Layers:
      - !Ref ModulesLayer

Resources:
  ModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layers/modules

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Env

  AddReactionHookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/add_reaction_hook
      Handler: index.handler
      Environment:
        Variables:
          TARGET_CHANNEL_ID: !Ref TargetChannelId
          TARGET_TOPIC_ARN: !Ref ParseReactionTopic
      Events:
        RestAPI:
          Type: HttpApi
          Properties:
            Path: /reaction
            Method: POST
            ApiId: !Ref HttpApi

  AddReactionHookLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_group.yml
      Parameters:
        FunctionName: !Ref AddReactionHookFunction

  ParseReactionTopic:
    Type: AWS::SNS::Topic

Outputs:
  BaseUrl:
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/{Env}

  AddReactionHookUrl:
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/{Env}/reaction